### ISSUE TITLE
Playlist response is broken after YouTube API update

### ISSUE THREAD

**Issue by 03stevensmi** [h0lg/SubTubular#1]
It was working last time I used this. I Installed everything (net core 3.1.11 & 3.1.13 desktop, runtime & server.
Now I get this error:

SubTubular search-channel https://www.youtube.com/channel/UC0rZoXAD5lxgBHMsjrGwWWQ --for "free speech,censorship,cancel culture,cancelculture,freespeech" --latest 500
Press any key to cancel

Unhandled exception. YoutubeExplode.Exceptions.TransientFailureException: Playlist response is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.Parse(String raw)
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.<>c__DisplayClass11_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.GetAsync(YoutubeHttpClient httpClient, String id, Int32 index)
   at YoutubeExplode.Playlists.PlaylistClient.GetVideosAsync(PlaylistId id)+MoveNext()
   at YoutubeExplode.Playlists.PlaylistClient.GetVideosAsync(PlaylistId id)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.ToListAsync[T](IAsyncEnumerable`1 asyncEnumerable)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.ToListAsync[T](IAsyncEnumerable`1 asyncEnumerable)
   at YoutubeExplode.AccessibilityExtensions.BufferAsync(IAsyncEnumerable`1 asyncVideoEnumerable)
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 40
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search[T](SearchCommand command, Func`2 getResultsAsync, Action`1 displayResult) in D:\projects\SubTubular\Program.cs:line 96
   at SubTubular.Program.Search[T](SearchCommand command, Func`2 getResultsAsync, Action`1 displayResult) in D:\projects\SubTubular\Program.cs:line 96
   at SubTubular.Program.<>c.<<Main>b__1_2>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 39
   at SubTubular.Program.<Main>(String[] args)

Will you be able to fix it?

**Comment by h0lg** [comment]
This seems to be working all right on my end - I can't reproduce the error. This part of the error message you posted suggests to me that this error may have been temporary:
> TransientFailureException: Playlist response is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.

@03stevensmi Does this error persist on your end with a verified working internet connection? If not, please close this issue. Thanks!

**Comment by 03stevensmi** [comment]
Yes the error persist on a verified working internet connection. 

Funny enough it was working a few month ago before I uninstalled net core 3.1. 
But now, no matter what version on net core 3.1 I run, I get that error every time.  

Can you tell me the exact net-core 3.1 installation exe you are using?. 
I've tried uninstalling net core 3.1.13 & installing 3.1.0 to see if that works. 
But it doesn't.

Same error on version 3.1.10 as well.
Tried on another pc as well and same issue. :(

>SubTubular search-videos egeCYaIe21Y gDrFdxWNk8c -f physician,physicist
Press any key to cancel

Unhandled exception. YoutubeExplode.Exceptions.TransientFailureException: Video watch page is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.<>c__DisplayClass9_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.GetAsync(YoutubeHttpClient httpClient, String videoId)
   at YoutubeExplode.Videos.VideoClient.GetVideoFromWatchPageAsync(VideoId id)
   at YoutubeExplode.Videos.VideoClient.GetAsync(VideoId id)
   at SubTubular.Youtube.GetVideoAsync(String videoId, Video alreadyLoaded) in D:\projects\SubTubular\Youtube.cs:line 165
   at SubTubular.Youtube.SearchVideosAsync(SearchVideos command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 78
   at SubTubular.Youtube.SearchVideosAsync(SearchVideos command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search[T](SearchCommand command, Func`2 getResultsAsync, Action`1 displayResult) in D:\projects\SubTubular\Program.cs:line 96
   at SubTubular.Program.Search[T](SearchCommand command, Func`2 getResultsAsync, Action`1 displayResult) in D:\projects\SubTubular\Program.cs:line 96
   at SubTubular.Program.<>c.<<Main>b__1_4>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 47
   at SubTubular.Program.<Main>(String[] args)

**Comment by 03stevensmi** [comment]
Now I've got this error. Can you take a look:

SubTubular search-videos egeCYaIe21Y gDrFdxWNk8c -f physician,physicist
Press any key to cancel

Unhandled exception. YoutubeExplode.Exceptions.FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
In most cases, this error indicates that YouTube most likely changed something, which broke the library.
If this issue persists, please report it on the project's GitHub page.

Method: GET, RequestUri: 'https://www.youtube.com/get_video_info?video_id=egeCYaIe21Y&el=embedded&eurl=https://youtube.googleapis.com/v/egeCYaIe21Y&hl=en&sts=', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64)
  User-Agent: AppleWebKit/537.36
  User-Agent: (KHTML, like Gecko)
  User-Agent: Chrome/80.0.3987.163
  User-Agent: Safari/537.36
  Accept-Encoding: gzip
  Accept-Encoding: deflate
}

StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  X-Frame-Options: SAMEORIGIN
  Cache-Control: no-cache
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000
  Date: Tue, 18 May 2021 17:02:15 GMT
  Server: YouTube
  Server: Frontend
  Server: Proxy
  X-XSS-Protection: 0
  Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
  Content-Type: text/html; charset=utf-8
  Expires: Tue, 27 Apr 1971 19:44:06 GMT
  Content-Length: 0
}
   at YoutubeExplode.ReverseEngineering.YoutubeHttpClient.CheckResponse(HttpResponseMessage response)
   at YoutubeExplode.ReverseEngineering.YoutubeHttpClient.GetStringAsync(String requestUri, Boolean ensureSuccess)
   at YoutubeExplode.ReverseEngineering.Responses.VideoInfoResponse.<>c__DisplayClass10_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.ReverseEngineering.Responses.VideoInfoResponse.GetAsync(YoutubeHttpClient httpClient, String videoId, String sts)
   at YoutubeExplode.Videos.VideoClient.GetVideoFromWatchPageAsync(VideoId id)
   at YoutubeExplode.Videos.VideoClient.GetAsync(VideoId id)
   at SubTubular.Youtube.GetVideoAsync(String videoId, Video alreadyLoaded) in D:\projects\SubTubular\Youtube.cs:line 165
   at SubTubular.Youtube.SearchVideosAsync(SearchVideos command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 78
   at SubTubular.Youtube.SearchVideosAsync(SearchVideos command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search[T](SearchCommand command, Func`2 getResultsAsync, Action`1 displayResult) in D:\projects\SubTubular\Program.cs:line 96
   at SubTubular.Program.Search[T](SearchCommand command, Func`2 getResultsAsync, Action`1 displayResult) in D:\projects\SubTubular\Program.cs:line 96
   at SubTubular.Program.<>c.<<Main>b__1_4>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 47
   at SubTubular.Program.<Main>(String[] args)

**Comment by 03stevensmi** [comment]
Yeah, the issue is happening to my friend as well. Same error message. I got him to try it out.
Is there anything you can do?
Maybe tell me what version of net core you use?
I've tried the oldest, the versions from the uploaded date of this github project, newest and so far... They all
Come with the exact same error. Both on 2 different pc's and on my mates pc who knows a lot more than I do.
Any help? Cheers!

**Comment by h0lg** [comment]
Thanks for reporting this issue - finally got around to fixing it. The problem was indeed a change in the YouTube API. Please check out version 2.0.0!
