### ISSUE TITLE
app crashes when encountering malformed or missing caption tracks

### ISSUE THREAD

**Issue by 03stevensmi** [h0lg/SubTubular#3]
Hey man,
After your latest fix, all was working great.

But now I can't do a full search.

The issue is it ether doesn't search anything period,
Or it searches the first few videos, then throws an error.

Could you take a look?

Here is the log:

SubTubular search-user DangerousVHS -f finally -h 0
Press any key to cancel

20/06/2021 23:00 https://youtu.be/SlNBoK8nVc4
  English (auto-generated)
    16:07 she finally got to the tree and the moon    https://youtu.be/SlNBoK8nVc4?t=967
  English (Canada)
    16:07 She finally got to the tree,    https://youtu.be/SlNBoK8nVc4?t=967

20/06/2021 23:00 https://youtu.be/aCvhq22mvBI
  English (auto-generated)
    17:49 let's go to mushrooms and i can finally    https://youtu.be/aCvhq22mvBI?t=1069
    18:23 we're finally home and everyone is safe    https://youtu.be/aCvhq22mvBI?t=1103
  English (Canada)
    17:51 and I can finally prove to you all what I saw.    https://youtu.be/aCvhq22mvBI?t=1071
    18:23 - We're finally home and everyone is safe.    https://youtu.be/aCvhq22mvBI?t=1103

19/06/2021 23:00 https://youtu.be/k17jeh0J6Zg
  English (auto-generated)
    17:16 finally done that story that's wonderful    https://youtu.be/k17jeh0J6Zg?t=1036
  English (Canada)
    17:17 I'm finally done that story.    https://youtu.be/k17jeh0J6Zg?t=1037

24/03/2021 00:00 https://youtu.be/y8Ct1fRFJIE
  English (auto-generated)
    19:08 hey the remote for the dvd i finally    https://youtu.be/y8Ct1fRFJIE?t=1148

24/03/2021 00:00 https://youtu.be/Y2ma6Vqrpxw
  English (auto-generated)
    07:19 means she finally has a boyfriend    https://youtu.be/Y2ma6Vqrpxw?t=439
    20:24 we are finally rid of bobby the butcher    https://youtu.be/Y2ma6Vqrpxw?t=1224

24/03/2021 00:00 https://youtu.be/lgS5IEd_pNE
  English (auto-generated)
    09:53 allowed me to finally clean my gutters    https://youtu.be/lgS5IEd_pNE?t=593

17/02/2021 00:00 https://youtu.be/31vOWexFw1U
  English (auto-generated)
    26:25 flat he paused looked hurt and finally    https://youtu.be/31vOWexFw1U?t=1585

20/01/2021 00:00 https://youtu.be/uN_rP9u_4t8
  in description: Finally reuploaded with fixed video.

> SubTubular search-user DangerousVHS -f finally -h 0

YoutubeExplode.Exceptions.YoutubeExplodeException: Could not extract caption part offset.
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.<>c.<GetAsync>b__3_1(ClosedCaptionPartExtractor p) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 104
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at YoutubeExplode.Utils.Extensions.CollectionExtensions.WhereNotNull[T](IEnumerable`1 source)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\CollectionExtensions.cs:line 10
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.<>c.<GetAsync>b__3_0(ClosedCaptionExtractor c) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 96
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at YoutubeExplode.Utils.Extensions.CollectionExtensions.WhereNotNull[T](IEnumerable`1 source)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\CollectionExtensions.cs:line 10
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.GetAsync(ClosedCaptionTrackInfo trackInfo, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 80
   at SubTubular.Youtube.DownloadCaptionTracksAsync(String videoId, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 189
   at SubTubular.Youtube.DownloadCaptionTracksAsync(String videoId, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Youtube.GetVideoAsync(String videoId, CancellationToken cancellation) in D:\projects\SubTubular\Youtube.cs:line 161
   at SubTubular.Youtube.GetVideoAsync(String videoId, CancellationToken cancellation) in D:\projects\SubTubular\Youtube.cs:line 161
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 45
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 40
The following error occurred and we were unabled to write a log for it.
> SubTubular search-user DangerousVHS -f finally -h 0
YoutubeExplode.Exceptions.YoutubeExplodeException: Could not extract caption part offset.
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.<>c.<GetAsync>b__3_1(ClosedCaptionPartExtractor p) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 104
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at YoutubeExplode.Utils.Extensions.CollectionExtensions.WhereNotNull[T](IEnumerable`1 source)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\CollectionExtensions.cs:line 10
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.<>c.<GetAsync>b__3_0(ClosedCaptionExtractor c) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 96
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at YoutubeExplode.Utils.Extensions.CollectionExtensions.WhereNotNull[T](IEnumerable`1 source)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\CollectionExtensions.cs:line 10
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.GetAsync(ClosedCaptionTrackInfo trackInfo, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 80
   at SubTubular.Youtube.DownloadCaptionTracksAsync(String videoId, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 189
   at SubTubular.Youtube.DownloadCaptionTracksAsync(String videoId, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Youtube.GetVideoAsync(String videoId, CancellationToken cancellation) in D:\projects\SubTubular\Youtube.cs:line 161
   at SubTubular.Youtube.GetVideoAsync(String videoId, CancellationToken cancellation) in D:\projects\SubTubular\Youtube.cs:line 161
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 45
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 40

Check out https://github.com/h0lg/SubTubular/issues for existing reports of this error and maybe a solution or work-around. If you want to report it, you can do that there to. Please make sure to supply the error details. Thanks!

**Comment by 03stevensmi** [comment]
Also I forgot to mention i can not search some long videos too.

Here's the error log for that too:

SubTubular search-playlist PLR_wPBd-QBP8pSLtkQ2NQiOjn-GjR8Xvf -f bath

YoutubeExplode.Exceptions.YoutubeExplodeException: Could not extract caption duration.
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.<>c.<GetAsync>b__3_0(ClosedCaptionExtractor c) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 84
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at YoutubeExplode.Utils.Extensions.CollectionExtensions.WhereNotNull[T](IEnumerable`1 source)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\CollectionExtensions.cs:line 10
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.GetAsync(ClosedCaptionTrackInfo trackInfo, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 80
   at SubTubular.Youtube.DownloadCaptionTracksAsync(String videoId, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 189
   at SubTubular.Youtube.DownloadCaptionTracksAsync(String videoId, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Youtube.GetVideoAsync(String videoId, CancellationToken cancellation) in D:\projects\SubTubular\Youtube.cs:line 161
   at SubTubular.Youtube.GetVideoAsync(String videoId, CancellationToken cancellation) in D:\projects\SubTubular\Youtube.cs:line 161
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 45
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.<>c__DisplayClass2_0.<<Main>b__3>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 46
The following error occurred and we were unabled to write a log for it.
> SubTubular search-playlist PLR_wPBd-QBP8pSLtkQ2NQiOjn-GjR8Xvf -f bath
YoutubeExplode.Exceptions.YoutubeExplodeException: Could not extract caption duration.
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.<>c.<GetAsync>b__3_0(ClosedCaptionExtractor c) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 84
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at YoutubeExplode.Utils.Extensions.CollectionExtensions.WhereNotNull[T](IEnumerable`1 source)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\CollectionExtensions.cs:line 10
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.GetAsync(ClosedCaptionTrackInfo trackInfo, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Videos\ClosedCaptions\ClosedCaptionClient.cs:line 80
   at SubTubular.Youtube.DownloadCaptionTracksAsync(String videoId, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 189
   at SubTubular.Youtube.DownloadCaptionTracksAsync(String videoId, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Youtube.GetVideoAsync(String videoId, CancellationToken cancellation) in D:\projects\SubTubular\Youtube.cs:line 161
   at SubTubular.Youtube.GetVideoAsync(String videoId, CancellationToken cancellation) in D:\projects\SubTubular\Youtube.cs:line 161
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 45
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.<>c__DisplayClass2_0.<<Main>b__3>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 46

Check out https://github.com/h0lg/SubTubular/issues for existing reports of this error and maybe a solution or work-around. If you want to report it, you can do that there to. Please make sure to supply the error details. Thanks!

I hope you can fix this,
Thank you for doing your amazing work! 
This is the most helpful tool I've ever came across for my research!

**Comment by 03stevensmi** [comment]
Also just found a new error. This one is stopping me from searching a user id:

Here is the log for this one too:

SubTubular search-user ToonGods -f finally -h 0

System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Bridge.YoutubeController.SendHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Bridge\YoutubeController.cs:line 57
   at YoutubeExplode.Bridge.YoutubeController.SendHttpRequestAsync(String url, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Bridge\YoutubeController.cs:line 65
   at YoutubeExplode.Bridge.YoutubeController.GetChannelPageAsync(String channelRoute, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Bridge\YoutubeController.cs:line 76
   at YoutubeExplode.Bridge.YoutubeController.GetChannelPageAsync(UserName userName, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Bridge\YoutubeController.cs:line 97
   at YoutubeExplode.Channels.ChannelClient.GetByUserAsync(UserName userName, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Channels\ChannelClient.cs:line 79
   at SubTubular.SearchUser.GetVideosAsync(YoutubeClient youtube, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Commands.cs:line 77
   at SubTubular.SearchUser.GetVideosAsync(YoutubeClient youtube, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.TakeAsync[T](IAsyncEnumerable`1 source, Int32 count)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 13
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.TakeAsync[T](IAsyncEnumerable`1 source, Int32 count)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 13
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.TakeAsync[T](IAsyncEnumerable`1 source, Int32 count)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 47
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 47
   at YoutubeExplode.Common.BatchItemExtensions.CollectAsync[T](IAsyncEnumerable`1 source, Int32 count) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Common\IBatchItem.cs:line 37
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 38
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 40
The following error occurred and we were unabled to write a log for it.
> SubTubular search-user ToonGods -f finally -h 0
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Bridge.YoutubeController.SendHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Bridge\YoutubeController.cs:line 57
   at YoutubeExplode.Bridge.YoutubeController.SendHttpRequestAsync(String url, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Bridge\YoutubeController.cs:line 65
   at YoutubeExplode.Bridge.YoutubeController.GetChannelPageAsync(String channelRoute, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Bridge\YoutubeController.cs:line 76
   at YoutubeExplode.Bridge.YoutubeController.GetChannelPageAsync(UserName userName, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Bridge\YoutubeController.cs:line 97
   at YoutubeExplode.Channels.ChannelClient.GetByUserAsync(UserName userName, CancellationToken cancellationToken) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Channels\ChannelClient.cs:line 79
   at SubTubular.SearchUser.GetVideosAsync(YoutubeClient youtube, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Commands.cs:line 77
   at SubTubular.SearchUser.GetVideosAsync(YoutubeClient youtube, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.TakeAsync[T](IAsyncEnumerable`1 source, Int32 count)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 13
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.TakeAsync[T](IAsyncEnumerable`1 source, Int32 count)+MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 13
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.TakeAsync[T](IAsyncEnumerable`1 source, Int32 count)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 47
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 47
   at YoutubeExplode.Common.BatchItemExtensions.CollectAsync[T](IAsyncEnumerable`1 source, Int32 count) in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Common\IBatchItem.cs:line 37
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\Youtube.cs:line 38
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.Search(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\Program.cs:line 122
   at SubTubular.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext() in D:\projects\SubTubular\Program.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\Program.cs:line 40

Check out https://github.com/h0lg/SubTubular/issues for existing reports of this error and maybe a solution or work-around. If you want to report it, you can do that there to. Please make sure to supply the error details. Thanks!

**Comment by h0lg** [comment]
Hey @03stevensmi,

thanks for the error reports and the examples that enabled me to reproduce them.
The errors you ran into were caused by malformed or missing caption tracks for some of the videos in the playlists you were searching - unfortunately interrupting the search on the first error :/

I'm catching those in the [new version 2.1.1](https://github.com/h0lg/SubTubular/releases/tag/v2.1.1) so that the search continues with other videos in the playlist and will - given some time - investigate whether some of the caption errors can be avoided or worked around in [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode), which is the library SubTubular uses to do the heavy lifting and grab the data off YouTube.

> Thank you for doing your amazing work!
> This is the most helpful tool I've ever came across for my research!

That makes me very happy :) Glad you find it useful, my dude.
Happy searching!
