### ISSUE TITLE
cant use the Nearness symbol in the latest version 3.0.1

### ISSUE THREAD

**Issue by 111100001** [h0lg/SubTubular#6]
it gives this error:

![image](https://github.com/h0lg/SubTubular/assets/24229327/b5e833ee-1283-4c4e-a927-177623b1b3ba)

**Comment by 111100001** [comment]
> SubTubular.exe search-channel https://www.youtube.com/@supertfVODs --for Uber~stole --top 500 --pad 40 -r uploaded asc

on Microsoft Windows NT 10.0.22631.0 .NET 7.0.13 SubTubular 3.0.1+7eda30ff

System.AggregateException: One or more errors occurred. (Error parsing query from --for | -f parameter: An unexpected operator was encountered: NearOperator) (Error parsing query from --for | -f parameter: An unexpected operator was encountered: NearOperator)
 ---> SubTubular.InputException: Error parsing query from --for | -f parameter: An unexpected operator was encountered: NearOperator
 ---> Lifti.Querying.QueryParserException: An unexpected operator was encountered: NearOperator
   at Lifti.Querying.QueryParser.CombineParts(IQueryPart existingPart, IQueryPart newPart, QueryTokenType operatorType, Int32 tolerance) in D:\a\1\s\src\Lifti.Core\Querying\QueryParser.cs:line 169
   at Lifti.Querying.QueryParser.CreateQueryPart(IIndexedFieldLookup fieldLookup, QueryParserState state, QueryToken token, IQueryPart currentQuery) in D:\a\1\s\src\Lifti.Core\Querying\QueryParser.cs:line 71
   at Lifti.Querying.QueryParser.Parse(IIndexedFieldLookup fieldLookup, String queryText, IIndexTokenizerProvider tokenizerProvider) in D:\a\1\s\src\Lifti.Core\Querying\QueryParser.cs:line 41
   at Lifti.FullTextIndex`1.Search(String searchText) in D:\a\1\s\src\Lifti.Core\FullTextIndex.cs:line 252
   at SubTubular.VideoIndex.SearchAsync(SearchCommand command, Func`3 getVideoAsync, CancellationToken cancellation, IDictionary`2 relevantVideos, Func`2 updatePlaylistVideosUploaded)+MoveNext() in D:\projects\SubTubular\SubTubular\VideoIndex.cs:line 133
   --- End of inner exception stack trace ---
   at SubTubular.VideoIndex.SearchAsync(SearchCommand command, Func`3 getVideoAsync, CancellationToken cancellation, IDictionary`2 relevantVideos, Func`2 updatePlaylistVideosUploaded)+MoveNext() in D:\projects\SubTubular\SubTubular\VideoIndex.cs:line 134
   at SubTubular.VideoIndex.SearchAsync(SearchCommand command, Func`3 getVideoAsync, CancellationToken cancellation, IDictionary`2 relevantVideos, Func`2 updatePlaylistVideosUploaded)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Youtube.<>c__DisplayClass5_0.<<SearchPlaylistAsync>b__2>d.MoveNext() in D:\projects\SubTubular\SubTubular\Youtube.cs:line 46
--- End of stack trace from previous location ---
   at SubTubular.Youtube.<>c__DisplayClass5_0.<<SearchPlaylistAsync>b__2>d.MoveNext() in D:\projects\SubTubular\SubTubular\Youtube.cs:line 46
   --- End of inner exception stack trace ---
   at SubTubular.Youtube.<>c__DisplayClass5_0.<SearchPlaylistAsync>b__4(Task t) in D:\projects\SubTubular\SubTubular\Youtube.cs:line 66
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+MoveNext() in D:\projects\SubTubular\SubTubular\Youtube.cs:line 76
   at SubTubular.Youtube.SearchPlaylistAsync(SearchPlaylistCommand command, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Program.SearchAsync(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\SubTubular\Program.cs:line 150
   at SubTubular.Program.SearchAsync(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\SubTubular\Program.cs:line 150
   at SubTubular.Program.SearchAsync(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\SubTubular\Program.cs:line 172
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\SubTubular\Program.cs:line 35
 ---> (Inner Exception #1) SubTubular.InputException: Error parsing query from --for | -f parameter: An unexpected operator was encountered: NearOperator
 ---> Lifti.Querying.QueryParserException: An unexpected operator was encountered: NearOperator
   at Lifti.Querying.QueryParser.CombineParts(IQueryPart existingPart, IQueryPart newPart, QueryTokenType operatorType, Int32 tolerance) in D:\a\1\s\src\Lifti.Core\Querying\QueryParser.cs:line 169
   at Lifti.Querying.QueryParser.CreateQueryPart(IIndexedFieldLookup fieldLookup, QueryParserState state, QueryToken token, IQueryPart currentQuery) in D:\a\1\s\src\Lifti.Core\Querying\QueryParser.cs:line 71
   at Lifti.Querying.QueryParser.Parse(IIndexedFieldLookup fieldLookup, String queryText, IIndexTokenizerProvider tokenizerProvider) in D:\a\1\s\src\Lifti.Core\Querying\QueryParser.cs:line 41
   at Lifti.FullTextIndex`1.Search(String searchText) in D:\a\1\s\src\Lifti.Core\FullTextIndex.cs:line 252
   at SubTubular.VideoIndex.SearchAsync(SearchCommand command, Func`3 getVideoAsync, CancellationToken cancellation, IDictionary`2 relevantVideos, Func`2 updatePlaylistVideosUploaded)+MoveNext() in D:\projects\SubTubular\SubTubular\VideoIndex.cs:line 133
   --- End of inner exception stack trace ---
   at SubTubular.VideoIndex.SearchAsync(SearchCommand command, Func`3 getVideoAsync, CancellationToken cancellation, IDictionary`2 relevantVideos, Func`2 updatePlaylistVideosUploaded)+MoveNext() in D:\projects\SubTubular\SubTubular\VideoIndex.cs:line 134
   at SubTubular.VideoIndex.SearchAsync(SearchCommand command, Func`3 getVideoAsync, CancellationToken cancellation, IDictionary`2 relevantVideos, Func`2 updatePlaylistVideosUploaded)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Youtube.SearchUnindexedVideos(SearchPlaylistCommand command, String[] unIndexedVideoIds, VideoIndex index, CancellationToken cancellation, Func`2 updatePlaylistVideosUploaded)+MoveNext() in D:\projects\SubTubular\SubTubular\Youtube.cs:line 205
   at SubTubular.Youtube.SearchUnindexedVideos(SearchPlaylistCommand command, String[] unIndexedVideoIds, VideoIndex index, CancellationToken cancellation, Func`2 updatePlaylistVideosUploaded)+MoveNext() in D:\projects\SubTubular\SubTubular\Youtube.cs:line 205
   at SubTubular.Youtube.SearchUnindexedVideos(SearchPlaylistCommand command, String[] unIndexedVideoIds, VideoIndex index, CancellationToken cancellation, Func`2 updatePlaylistVideosUploaded)+MoveNext() in D:\projects\SubTubular\SubTubular\Youtube.cs:line 183
   at SubTubular.Youtube.SearchUnindexedVideos(SearchPlaylistCommand command, String[] unIndexedVideoIds, VideoIndex index, CancellationToken cancellation, Func`2 updatePlaylistVideosUploaded)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at SubTubular.Youtube.<>c__DisplayClass5_0.<<SearchPlaylistAsync>b__3>d.MoveNext() in D:\projects\SubTubular\SubTubular\Youtube.cs:line 57
--- End of stack trace from previous location ---
   at SubTubular.Youtube.<>c__DisplayClass5_0.<<SearchPlaylistAsync>b__3>d.MoveNext() in D:\projects\SubTubular\SubTubular\Youtube.cs:line 57<---

**Comment by 111100001** [comment]
fixed.  had to put a space between the nearness operator

**Comment by h0lg** [comment]
You got it. Instead of
`search-channel @supertfVODs --for Uber~stole --top 500 --pad 40 -r uploaded asc`
put spaces around the nearness operator `~` like
`search-channel @supertfVODs --for Uber ~ stole --top 500 --pad 40 -r uploaded asc`
