### ISSUE TITLE
Channel page is broken after YouTube API update

### ISSUE THREAD

**Issue by 03stevensmi** [h0lg/SubTubular#9]
Hey Man,
I got a new error message today that is stopping me from using subtubular.

here is the log file:
` 
> SubTubular.exe c copastudio -t 110 -f animacao

on Microsoft Windows NT 10.0.19041.0 .NET 7.0.19 SubTubular 3.0.1+7eda30ff

System.AggregateException: Unexpected errors identifying channel 'copastudio'. (Channel page is broken. Please try again in a few minutes.) (Channel page is broken. Please try again in a few minutes.) (Channel page is broken. Please try again in a few minutes.)
 ---> YoutubeExplode.Exceptions.YoutubeExplodeException: Channel page is broken. Please try again in a few minutes.
   at YoutubeExplode.Channels.ChannelController.GetChannelPageAsync(String channelRoute, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelController.cs:line 34
   at YoutubeExplode.Channels.ChannelController.GetChannelPageAsync(ChannelHandle channelHandle, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelController.cs:line 61
   at YoutubeExplode.Channels.ChannelClient.GetByHandleAsync(ChannelHandle channelHandle, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelClient.cs:line 107
   at SubTubular.SearchChannel.<>c__DisplayClass10_0.<<RemoteValidateAsync>g__GetChannelAliasMap|4>d.MoveNext() in D:\projects\SubTubular\SubTubular\SearchChannel.cs:line 108
--- End of stack trace from previous location ---
   at SubTubular.ValueTasks.WhenAll[T](IReadOnlyList`1 tasks) in D:\projects\SubTubular\SubTubular\Extensions.cs:line 108
   --- End of inner exception stack trace ---
   at SubTubular.SearchChannel.RemoteValidateAsync(YoutubeClient youtube, DataStore dataStore, CancellationToken cancellation) in D:\projects\SubTubular\SubTubular\SearchChannel.cs:line 67
   at SubTubular.Program.SearchAsync(SearchCommand command, String originalCommand, Func`2 getResultsAsync) in D:\projects\SubTubular\SubTubular\Program.cs:line 125
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at SubTubular.Program.Main(String[] args) in D:\projects\SubTubular\SubTubular\Program.cs:line 35
 ---> (Inner Exception #1) YoutubeExplode.Exceptions.YoutubeExplodeException: Channel page is broken. Please try again in a few minutes.
   at YoutubeExplode.Channels.ChannelController.GetChannelPageAsync(String channelRoute, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelController.cs:line 34
   at YoutubeExplode.Channels.ChannelController.GetChannelPageAsync(ChannelSlug channelSlug, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelController.cs:line 56
   at YoutubeExplode.Channels.ChannelClient.GetBySlugAsync(ChannelSlug channelSlug, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelClient.cs:line 99
   at SubTubular.SearchChannel.<>c__DisplayClass10_0.<<RemoteValidateAsync>g__GetChannelAliasMap|4>d.MoveNext() in D:\projects\SubTubular\SubTubular\SearchChannel.cs:line 108
--- End of stack trace from previous location ---
   at SubTubular.ValueTasks.WhenAll[T](IReadOnlyList`1 tasks) in D:\projects\SubTubular\SubTubular\Extensions.cs:line 108<---

 ---> (Inner Exception #2) YoutubeExplode.Exceptions.YoutubeExplodeException: Channel page is broken. Please try again in a few minutes.
   at YoutubeExplode.Channels.ChannelController.GetChannelPageAsync(String channelRoute, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelController.cs:line 34
   at YoutubeExplode.Channels.ChannelController.GetChannelPageAsync(UserName userName, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelController.cs:line 51
   at YoutubeExplode.Channels.ChannelClient.GetByUserAsync(UserName userName, CancellationToken cancellationToken) in /_/YoutubeExplode/Channels/ChannelClient.cs:line 91
   at SubTubular.SearchChannel.<>c__DisplayClass10_0.<<RemoteValidateAsync>g__GetChannelAliasMap|4>d.MoveNext() in D:\projects\SubTubular\SubTubular\SearchChannel.cs:line 108
--- End of stack trace from previous location ---
   at SubTubular.ValueTasks.WhenAll[T](IReadOnlyList`1 tasks) in D:\projects\SubTubular\SubTubular\Extensions.cs:line 108<--- 
`

Ia this normal?, or does it need to be fixed.

Cheers,
03stevensmi

**Comment by h0lg** [comment]
@03stevensmi  Thanks for the report - https://github.com/h0lg/SubTubular/releases/tag/v3.1.0 should fix that. Good luck!
